### ISSUE TITLE
XMLファイル名と画像ファイル名の不一致

### ISSUE THREAD

**Issue by s4k10503** [Kazuhito00/convert_coco_to_voc#1]
こんにちは。
生成された XML ファイル名が画像ファイル名と一致しないのは仕様でしょうか?
元のVOCデータセットを確認すると、XMLファイルと画像ファイルの名前は一致しているようです。
この点を修正するPR を受けつけていただけますか?

Hi.
Is it by design that the generated XML file name does not match the image file name?
When I check the original VOC dataset, the names of the XML and image files seem to match.
Could you please accept a PR to fix this?

**Comment by Kazuhito00** [comment]
こんにちは。

> 生成された XML ファイル名が画像ファイル名と一致しないのは仕様でしょうか?

　zfillをしている箇所ですね。
　元々このリポジトリで変換を想定していたVOC形式は、ファイル名が数値の連番を想定していたため、
　そのような処理になってしまっていました。

> この点を修正するPR を受けつけていただけますか?

　上記の問題が放置されていた状況のため、より汎用的になるPRは歓迎です。
